//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaegerMeister.MvvmSample.Logic.Ui
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Login
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Login()
        {
            this.tbl_Abfrage = new HashSet<tbl_Abfrage>();
        }
    
        public int Login_ID { get; set; }
        public string Loginname { get; set; }
        public string Passwort { get; set; }
        public System.DateTime DatumUhrzeit { get; set; }
        public string Antwort { get; set; }
        public string UserVorname { get; set; }
        public string UserNachname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Abfrage> tbl_Abfrage { get; set; }
    }
}
