//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaegerMeister.MvvmSample.Logic.Ui
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Rueckmeldung
    {
        public int Rückmeldung_ID { get; set; }
        public string Funktion { get; set; }
        public int Gäste { get; set; }
        public int Jäger_ID { get; set; }
        public int Termine_ID { get; set; }
    
        public virtual tbl_Jaeger tbl_Jaeger { get; set; }
        public virtual tbl_Termine tbl_Termine { get; set; }
    }
}
