//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaegerMeister.MvvmSample.Logic.Ui
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Abfrage
    {
        public int Abfrage_ID { get; set; }
        public int Sicherheitsfragen_ID { get; set; }
        public int Login_ID { get; set; }
    
        public virtual tbl_Login tbl_Login { get; set; }
        public virtual tbl_Sicherheitsfragen tbl_Sicherheitsfragen { get; set; }
    }
}
