//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaegerMeister.MvvmSample.Logic.Ui
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Abfrage
    {
        public int Abfrage_ID { get; set; }
        public int Sicherheitsfragen_ID { get; set; }
        public int Login_ID { get; set; }
    
        public virtual tbl_Login tbl_Login { get; set; }
        public virtual tbl_Sicherheitsfragen tbl_Sicherheitsfragen { get; set; }
    }
}
