//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaegerMeister.MvvmSample.Logic.Ui
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Termine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Termine()
        {
            this.tbl_Jagderfolge = new HashSet<tbl_Jagderfolge>();
            this.tbl_Postausgang = new HashSet<tbl_Postausgang>();
            this.tbl_Rueckmeldung = new HashSet<tbl_Rueckmeldung>();
        }
    
        public int Termine_ID { get; set; }
        public string Ort { get; set; }
        public System.DateTime DatumUhrzeit { get; set; }
        public string Bezeichnung { get; set; }
        public string Typ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Jagderfolge> tbl_Jagderfolge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Postausgang> tbl_Postausgang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Rueckmeldung> tbl_Rueckmeldung { get; set; }
    }
}
