//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaegerMeister.MvvmSample.Logic.Ui
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Abschussliste
    {
        public int Abschussliste_ID { get; set; }
        public int Anzahl { get; set; }
        public System.DateTime Jahr { get; set; }
        public int Tiere_ID { get; set; }
    
        public virtual tbl_Tiere tbl_Tiere { get; set; }
    }
}
